// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PathChecker is an autogenerated mock type for the PathChecker type
type PathChecker struct {
	mock.Mock
}
