// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPathModifier creates a new instance of PathModifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPathModifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *PathModifier {
	mock := &PathModifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PathModifier is an autogenerated mock type for the PathModifier type
type PathModifier struct {
	mock.Mock
}

type PathModifier_Expecter struct {
	mock *mock.Mock
}

func (_m *PathModifier) EXPECT() *PathModifier_Expecter {
	return &PathModifier_Expecter{mock: &_m.Mock}
}

// AbsPath provides a mock function for the type PathModifier
func (_mock *PathModifier) AbsPath(pth string) (string, error) {
	ret := _mock.Called(pth)

	if len(ret) == 0 {
		panic("no return value specified for AbsPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(pth)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(pth)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PathModifier_AbsPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbsPath'
type PathModifier_AbsPath_Call struct {
	*mock.Call
}

// AbsPath is a helper method to define mock.On call
//   - pth string
func (_e *PathModifier_Expecter) AbsPath(pth interface{}) *PathModifier_AbsPath_Call {
	return &PathModifier_AbsPath_Call{Call: _e.mock.On("AbsPath", pth)}
}

func (_c *PathModifier_AbsPath_Call) Run(run func(pth string)) *PathModifier_AbsPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PathModifier_AbsPath_Call) Return(s string, err error) *PathModifier_AbsPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PathModifier_AbsPath_Call) RunAndReturn(run func(pth string) (string, error)) *PathModifier_AbsPath_Call {
	_c.Call.Return(run)
	return _c
}

// EscapeGlobPath provides a mock function for the type PathModifier
func (_mock *PathModifier) EscapeGlobPath(path string) string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for EscapeGlobPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PathModifier_EscapeGlobPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EscapeGlobPath'
type PathModifier_EscapeGlobPath_Call struct {
	*mock.Call
}

// EscapeGlobPath is a helper method to define mock.On call
//   - path string
func (_e *PathModifier_Expecter) EscapeGlobPath(path interface{}) *PathModifier_EscapeGlobPath_Call {
	return &PathModifier_EscapeGlobPath_Call{Call: _e.mock.On("EscapeGlobPath", path)}
}

func (_c *PathModifier_EscapeGlobPath_Call) Run(run func(path string)) *PathModifier_EscapeGlobPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PathModifier_EscapeGlobPath_Call) Return(s string) *PathModifier_EscapeGlobPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PathModifier_EscapeGlobPath_Call) RunAndReturn(run func(path string) string) *PathModifier_EscapeGlobPath_Call {
	_c.Call.Return(run)
	return _c
}
