// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewFileManager creates a new instance of FileManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileManager {
	mock := &FileManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileManager is an autogenerated mock type for the FileManager type
type FileManager struct {
	mock.Mock
}

type FileManager_Expecter struct {
	mock *mock.Mock
}

func (_m *FileManager) EXPECT() *FileManager_Expecter {
	return &FileManager_Expecter{mock: &_m.Mock}
}

// CopyDir provides a mock function for the type FileManager
func (_mock *FileManager) CopyDir(src string, dst string) error {
	ret := _mock.Called(src, dst)

	if len(ret) == 0 {
		panic("no return value specified for CopyDir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(src, dst)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileManager_CopyDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyDir'
type FileManager_CopyDir_Call struct {
	*mock.Call
}

// CopyDir is a helper method to define mock.On call
//   - src string
//   - dst string
func (_e *FileManager_Expecter) CopyDir(src interface{}, dst interface{}) *FileManager_CopyDir_Call {
	return &FileManager_CopyDir_Call{Call: _e.mock.On("CopyDir", src, dst)}
}

func (_c *FileManager_CopyDir_Call) Run(run func(src string, dst string)) *FileManager_CopyDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileManager_CopyDir_Call) Return(err error) *FileManager_CopyDir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileManager_CopyDir_Call) RunAndReturn(run func(src string, dst string) error) *FileManager_CopyDir_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFile provides a mock function for the type FileManager
func (_mock *FileManager) CopyFile(src string, dst string) error {
	ret := _mock.Called(src, dst)

	if len(ret) == 0 {
		panic("no return value specified for CopyFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(src, dst)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileManager_CopyFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFile'
type FileManager_CopyFile_Call struct {
	*mock.Call
}

// CopyFile is a helper method to define mock.On call
//   - src string
//   - dst string
func (_e *FileManager_Expecter) CopyFile(src interface{}, dst interface{}) *FileManager_CopyFile_Call {
	return &FileManager_CopyFile_Call{Call: _e.mock.On("CopyFile", src, dst)}
}

func (_c *FileManager_CopyFile_Call) Run(run func(src string, dst string)) *FileManager_CopyFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileManager_CopyFile_Call) Return(err error) *FileManager_CopyFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileManager_CopyFile_Call) RunAndReturn(run func(src string, dst string) error) *FileManager_CopyFile_Call {
	_c.Call.Return(run)
	return _c
}

// FileSizeInBytes provides a mock function for the type FileManager
func (_mock *FileManager) FileSizeInBytes(pth string) (int64, error) {
	ret := _mock.Called(pth)

	if len(ret) == 0 {
		panic("no return value specified for FileSizeInBytes")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(pth)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(pth)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileManager_FileSizeInBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileSizeInBytes'
type FileManager_FileSizeInBytes_Call struct {
	*mock.Call
}

// FileSizeInBytes is a helper method to define mock.On call
//   - pth string
func (_e *FileManager_Expecter) FileSizeInBytes(pth interface{}) *FileManager_FileSizeInBytes_Call {
	return &FileManager_FileSizeInBytes_Call{Call: _e.mock.On("FileSizeInBytes", pth)}
}

func (_c *FileManager_FileSizeInBytes_Call) Run(run func(pth string)) *FileManager_FileSizeInBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_FileSizeInBytes_Call) Return(n int64, err error) *FileManager_FileSizeInBytes_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *FileManager_FileSizeInBytes_Call) RunAndReturn(run func(pth string) (int64, error)) *FileManager_FileSizeInBytes_Call {
	_c.Call.Return(run)
	return _c
}

// LastNLines provides a mock function for the type FileManager
func (_mock *FileManager) LastNLines(s string, n int) string {
	ret := _mock.Called(s, n)

	if len(ret) == 0 {
		panic("no return value specified for LastNLines")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = returnFunc(s, n)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FileManager_LastNLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastNLines'
type FileManager_LastNLines_Call struct {
	*mock.Call
}

// LastNLines is a helper method to define mock.On call
//   - s string
//   - n int
func (_e *FileManager_Expecter) LastNLines(s interface{}, n interface{}) *FileManager_LastNLines_Call {
	return &FileManager_LastNLines_Call{Call: _e.mock.On("LastNLines", s, n)}
}

func (_c *FileManager_LastNLines_Call) Run(run func(s string, n int)) *FileManager_LastNLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileManager_LastNLines_Call) Return(s1 string) *FileManager_LastNLines_Call {
	_c.Call.Return(s1)
	return _c
}

func (_c *FileManager_LastNLines_Call) RunAndReturn(run func(s string, n int) string) *FileManager_LastNLines_Call {
	_c.Call.Return(run)
	return _c
}

// Lstat provides a mock function for the type FileManager
func (_mock *FileManager) Lstat(path string) (os.FileInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Lstat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileManager_Lstat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lstat'
type FileManager_Lstat_Call struct {
	*mock.Call
}

// Lstat is a helper method to define mock.On call
//   - path string
func (_e *FileManager_Expecter) Lstat(path interface{}) *FileManager_Lstat_Call {
	return &FileManager_Lstat_Call{Call: _e.mock.On("Lstat", path)}
}

func (_c *FileManager_Lstat_Call) Run(run func(path string)) *FileManager_Lstat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_Lstat_Call) Return(v os.FileInfo, err error) *FileManager_Lstat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *FileManager_Lstat_Call) RunAndReturn(run func(path string) (os.FileInfo, error)) *FileManager_Lstat_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type FileManager
func (_mock *FileManager) Open(path string) (*os.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileManager_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type FileManager_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *FileManager_Expecter) Open(path interface{}) *FileManager_Open_Call {
	return &FileManager_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *FileManager_Open_Call) Run(run func(path string)) *FileManager_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_Open_Call) Return(file *os.File, err error) *FileManager_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *FileManager_Open_Call) RunAndReturn(run func(path string) (*os.File, error)) *FileManager_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenReaderIfExists provides a mock function for the type FileManager
func (_mock *FileManager) OpenReaderIfExists(path string) (io.Reader, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for OpenReaderIfExists")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (io.Reader, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileManager_OpenReaderIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenReaderIfExists'
type FileManager_OpenReaderIfExists_Call struct {
	*mock.Call
}

// OpenReaderIfExists is a helper method to define mock.On call
//   - path string
func (_e *FileManager_Expecter) OpenReaderIfExists(path interface{}) *FileManager_OpenReaderIfExists_Call {
	return &FileManager_OpenReaderIfExists_Call{Call: _e.mock.On("OpenReaderIfExists", path)}
}

func (_c *FileManager_OpenReaderIfExists_Call) Run(run func(path string)) *FileManager_OpenReaderIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_OpenReaderIfExists_Call) Return(reader io.Reader, err error) *FileManager_OpenReaderIfExists_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *FileManager_OpenReaderIfExists_Call) RunAndReturn(run func(path string) (io.Reader, error)) *FileManager_OpenReaderIfExists_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDirEntryNames provides a mock function for the type FileManager
func (_mock *FileManager) ReadDirEntryNames(path string) ([]string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDirEntryNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileManager_ReadDirEntryNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDirEntryNames'
type FileManager_ReadDirEntryNames_Call struct {
	*mock.Call
}

// ReadDirEntryNames is a helper method to define mock.On call
//   - path string
func (_e *FileManager_Expecter) ReadDirEntryNames(path interface{}) *FileManager_ReadDirEntryNames_Call {
	return &FileManager_ReadDirEntryNames_Call{Call: _e.mock.On("ReadDirEntryNames", path)}
}

func (_c *FileManager_ReadDirEntryNames_Call) Run(run func(path string)) *FileManager_ReadDirEntryNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_ReadDirEntryNames_Call) Return(strings []string, err error) *FileManager_ReadDirEntryNames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *FileManager_ReadDirEntryNames_Call) RunAndReturn(run func(path string) ([]string, error)) *FileManager_ReadDirEntryNames_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type FileManager
func (_mock *FileManager) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FileManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *FileManager_Expecter) Remove(path interface{}) *FileManager_Remove_Call {
	return &FileManager_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *FileManager_Remove_Call) Run(run func(path string)) *FileManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_Remove_Call) Return(err error) *FileManager_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileManager_Remove_Call) RunAndReturn(run func(path string) error) *FileManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type FileManager
func (_mock *FileManager) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileManager_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type FileManager_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *FileManager_Expecter) RemoveAll(path interface{}) *FileManager_RemoveAll_Call {
	return &FileManager_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *FileManager_RemoveAll_Call) Run(run func(path string)) *FileManager_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileManager_RemoveAll_Call) Return(err error) *FileManager_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileManager_RemoveAll_Call) RunAndReturn(run func(path string) error) *FileManager_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type FileManager
func (_mock *FileManager) Write(path string, value string, perm os.FileMode) error {
	ret := _mock.Called(path, value, perm)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, os.FileMode) error); ok {
		r0 = returnFunc(path, value, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileManager_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type FileManager_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - path string
//   - value string
//   - perm os.FileMode
func (_e *FileManager_Expecter) Write(path interface{}, value interface{}, perm interface{}) *FileManager_Write_Call {
	return &FileManager_Write_Call{Call: _e.mock.On("Write", path, value, perm)}
}

func (_c *FileManager_Write_Call) Run(run func(path string, value string, perm os.FileMode)) *FileManager_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FileManager_Write_Call) Return(err error) *FileManager_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileManager_Write_Call) RunAndReturn(run func(path string, value string, perm os.FileMode) error) *FileManager_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBytes provides a mock function for the type FileManager
func (_mock *FileManager) WriteBytes(path string, value []byte) error {
	ret := _mock.Called(path, value)

	if len(ret) == 0 {
		panic("no return value specified for WriteBytes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileManager_WriteBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBytes'
type FileManager_WriteBytes_Call struct {
	*mock.Call
}

// WriteBytes is a helper method to define mock.On call
//   - path string
//   - value []byte
func (_e *FileManager_Expecter) WriteBytes(path interface{}, value interface{}) *FileManager_WriteBytes_Call {
	return &FileManager_WriteBytes_Call{Call: _e.mock.On("WriteBytes", path, value)}
}

func (_c *FileManager_WriteBytes_Call) Run(run func(path string, value []byte)) *FileManager_WriteBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileManager_WriteBytes_Call) Return(err error) *FileManager_WriteBytes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileManager_WriteBytes_Call) RunAndReturn(run func(path string, value []byte) error) *FileManager_WriteBytes_Call {
	_c.Call.Return(run)
	return _c
}
