// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"
	"os"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewOsProxy creates a new instance of OsProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOsProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *OsProxy {
	mock := &OsProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OsProxy is an autogenerated mock type for the OsProxy type
type OsProxy struct {
	mock.Mock
}

type OsProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *OsProxy) EXPECT() *OsProxy_Expecter {
	return &OsProxy_Expecter{mock: &_m.Mock}
}

// Abs provides a mock function for the type OsProxy
func (_mock *OsProxy) Abs(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Abs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Abs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abs'
type OsProxy_Abs_Call struct {
	*mock.Call
}

// Abs is a helper method to define mock.On call
//   - path string
func (_e *OsProxy_Expecter) Abs(path interface{}) *OsProxy_Abs_Call {
	return &OsProxy_Abs_Call{Call: _e.mock.On("Abs", path)}
}

func (_c *OsProxy_Abs_Call) Run(run func(path string)) *OsProxy_Abs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Abs_Call) Return(s string, err error) *OsProxy_Abs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OsProxy_Abs_Call) RunAndReturn(run func(path string) (string, error)) *OsProxy_Abs_Call {
	_c.Call.Return(run)
	return _c
}

// Chmod provides a mock function for the type OsProxy
func (_mock *OsProxy) Chmod(name string, mode os.FileMode) error {
	ret := _mock.Called(name, mode)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(name, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type OsProxy_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - name string
//   - mode os.FileMode
func (_e *OsProxy_Expecter) Chmod(name interface{}, mode interface{}) *OsProxy_Chmod_Call {
	return &OsProxy_Chmod_Call{Call: _e.mock.On("Chmod", name, mode)}
}

func (_c *OsProxy_Chmod_Call) Run(run func(name string, mode os.FileMode)) *OsProxy_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OsProxy_Chmod_Call) Return(err error) *OsProxy_Chmod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Chmod_Call) RunAndReturn(run func(name string, mode os.FileMode) error) *OsProxy_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Chown provides a mock function for the type OsProxy
func (_mock *OsProxy) Chown(name string, uid int, gid int) error {
	ret := _mock.Called(name, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = returnFunc(name, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type OsProxy_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - name string
//   - uid int
//   - gid int
func (_e *OsProxy_Expecter) Chown(name interface{}, uid interface{}, gid interface{}) *OsProxy_Chown_Call {
	return &OsProxy_Chown_Call{Call: _e.mock.On("Chown", name, uid, gid)}
}

func (_c *OsProxy_Chown_Call) Run(run func(name string, uid int, gid int)) *OsProxy_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OsProxy_Chown_Call) Return(err error) *OsProxy_Chown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Chown_Call) RunAndReturn(run func(name string, uid int, gid int) error) *OsProxy_Chown_Call {
	_c.Call.Return(run)
	return _c
}

// Chtimes provides a mock function for the type OsProxy
func (_mock *OsProxy) Chtimes(name string, atime time.Time, mtime time.Time) error {
	ret := _mock.Called(name, atime, mtime)

	if len(ret) == 0 {
		panic("no return value specified for Chtimes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, time.Time) error); ok {
		r0 = returnFunc(name, atime, mtime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Chtimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chtimes'
type OsProxy_Chtimes_Call struct {
	*mock.Call
}

// Chtimes is a helper method to define mock.On call
//   - name string
//   - atime time.Time
//   - mtime time.Time
func (_e *OsProxy_Expecter) Chtimes(name interface{}, atime interface{}, mtime interface{}) *OsProxy_Chtimes_Call {
	return &OsProxy_Chtimes_Call{Call: _e.mock.On("Chtimes", name, atime, mtime)}
}

func (_c *OsProxy_Chtimes_Call) Run(run func(name string, atime time.Time, mtime time.Time)) *OsProxy_Chtimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OsProxy_Chtimes_Call) Return(err error) *OsProxy_Chtimes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Chtimes_Call) RunAndReturn(run func(name string, atime time.Time, mtime time.Time) error) *OsProxy_Chtimes_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type OsProxy
func (_mock *OsProxy) Create(name string) (*os.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OsProxy_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *OsProxy_Expecter) Create(name interface{}) *OsProxy_Create_Call {
	return &OsProxy_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *OsProxy_Create_Call) Run(run func(name string)) *OsProxy_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Create_Call) Return(file *os.File, err error) *OsProxy_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *OsProxy_Create_Call) RunAndReturn(run func(name string) (*os.File, error)) *OsProxy_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DirFS provides a mock function for the type OsProxy
func (_mock *OsProxy) DirFS(dir string) fs.FS {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for DirFS")
	}

	var r0 fs.FS
	if returnFunc, ok := ret.Get(0).(func(string) fs.FS); ok {
		r0 = returnFunc(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}
	return r0
}

// OsProxy_DirFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirFS'
type OsProxy_DirFS_Call struct {
	*mock.Call
}

// DirFS is a helper method to define mock.On call
//   - dir string
func (_e *OsProxy_Expecter) DirFS(dir interface{}) *OsProxy_DirFS_Call {
	return &OsProxy_DirFS_Call{Call: _e.mock.On("DirFS", dir)}
}

func (_c *OsProxy_DirFS_Call) Run(run func(dir string)) *OsProxy_DirFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_DirFS_Call) Return(fS fs.FS) *OsProxy_DirFS_Call {
	_c.Call.Return(fS)
	return _c
}

func (_c *OsProxy_DirFS_Call) RunAndReturn(run func(dir string) fs.FS) *OsProxy_DirFS_Call {
	_c.Call.Return(run)
	return _c
}

// Getwd provides a mock function for the type OsProxy
func (_mock *OsProxy) Getwd() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Getwd")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Getwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getwd'
type OsProxy_Getwd_Call struct {
	*mock.Call
}

// Getwd is a helper method to define mock.On call
func (_e *OsProxy_Expecter) Getwd() *OsProxy_Getwd_Call {
	return &OsProxy_Getwd_Call{Call: _e.mock.On("Getwd")}
}

func (_c *OsProxy_Getwd_Call) Run(run func()) *OsProxy_Getwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OsProxy_Getwd_Call) Return(s string, err error) *OsProxy_Getwd_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OsProxy_Getwd_Call) RunAndReturn(run func() (string, error)) *OsProxy_Getwd_Call {
	_c.Call.Return(run)
	return _c
}

// Lchown provides a mock function for the type OsProxy
func (_mock *OsProxy) Lchown(name string, uid int, gid int) error {
	ret := _mock.Called(name, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Lchown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = returnFunc(name, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Lchown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lchown'
type OsProxy_Lchown_Call struct {
	*mock.Call
}

// Lchown is a helper method to define mock.On call
//   - name string
//   - uid int
//   - gid int
func (_e *OsProxy_Expecter) Lchown(name interface{}, uid interface{}, gid interface{}) *OsProxy_Lchown_Call {
	return &OsProxy_Lchown_Call{Call: _e.mock.On("Lchown", name, uid, gid)}
}

func (_c *OsProxy_Lchown_Call) Run(run func(name string, uid int, gid int)) *OsProxy_Lchown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OsProxy_Lchown_Call) Return(err error) *OsProxy_Lchown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Lchown_Call) RunAndReturn(run func(name string, uid int, gid int) error) *OsProxy_Lchown_Call {
	_c.Call.Return(run)
	return _c
}

// Lstat provides a mock function for the type OsProxy
func (_mock *OsProxy) Lstat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Lstat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Lstat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lstat'
type OsProxy_Lstat_Call struct {
	*mock.Call
}

// Lstat is a helper method to define mock.On call
//   - name string
func (_e *OsProxy_Expecter) Lstat(name interface{}) *OsProxy_Lstat_Call {
	return &OsProxy_Lstat_Call{Call: _e.mock.On("Lstat", name)}
}

func (_c *OsProxy_Lstat_Call) Run(run func(name string)) *OsProxy_Lstat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Lstat_Call) Return(v os.FileInfo, err error) *OsProxy_Lstat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *OsProxy_Lstat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *OsProxy_Lstat_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function for the type OsProxy
func (_mock *OsProxy) Mkdir(name string, perm os.FileMode) error {
	ret := _mock.Called(name, perm)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(name, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type OsProxy_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - name string
//   - perm os.FileMode
func (_e *OsProxy_Expecter) Mkdir(name interface{}, perm interface{}) *OsProxy_Mkdir_Call {
	return &OsProxy_Mkdir_Call{Call: _e.mock.On("Mkdir", name, perm)}
}

func (_c *OsProxy_Mkdir_Call) Run(run func(name string, perm os.FileMode)) *OsProxy_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OsProxy_Mkdir_Call) Return(err error) *OsProxy_Mkdir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Mkdir_Call) RunAndReturn(run func(name string, perm os.FileMode) error) *OsProxy_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type OsProxy
func (_mock *OsProxy) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type OsProxy_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *OsProxy_Expecter) MkdirAll(path interface{}, perm interface{}) *OsProxy_MkdirAll_Call {
	return &OsProxy_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *OsProxy_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *OsProxy_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OsProxy_MkdirAll_Call) Return(err error) *OsProxy_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *OsProxy_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type OsProxy
func (_mock *OsProxy) Open(name string) (*os.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type OsProxy_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *OsProxy_Expecter) Open(name interface{}) *OsProxy_Open_Call {
	return &OsProxy_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *OsProxy_Open_Call) Run(run func(name string)) *OsProxy_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Open_Call) Return(file *os.File, err error) *OsProxy_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *OsProxy_Open_Call) RunAndReturn(run func(name string) (*os.File, error)) *OsProxy_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type OsProxy
func (_mock *OsProxy) OpenFile(name string, flag int, perm os.FileMode) (*os.File, error) {
	ret := _mock.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) (*os.File, error)); ok {
		return returnFunc(name, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) *os.File); ok {
		r0 = returnFunc(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, os.FileMode) error); ok {
		r1 = returnFunc(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type OsProxy_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm os.FileMode
func (_e *OsProxy_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *OsProxy_OpenFile_Call {
	return &OsProxy_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *OsProxy_OpenFile_Call) Run(run func(name string, flag int, perm os.FileMode)) *OsProxy_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OsProxy_OpenFile_Call) Return(file *os.File, err error) *OsProxy_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *OsProxy_OpenFile_Call) RunAndReturn(run func(name string, flag int, perm os.FileMode) (*os.File, error)) *OsProxy_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// Readlink provides a mock function for the type OsProxy
func (_mock *OsProxy) Readlink(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Readlink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Readlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readlink'
type OsProxy_Readlink_Call struct {
	*mock.Call
}

// Readlink is a helper method to define mock.On call
//   - name string
func (_e *OsProxy_Expecter) Readlink(name interface{}) *OsProxy_Readlink_Call {
	return &OsProxy_Readlink_Call{Call: _e.mock.On("Readlink", name)}
}

func (_c *OsProxy_Readlink_Call) Run(run func(name string)) *OsProxy_Readlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Readlink_Call) Return(s string, err error) *OsProxy_Readlink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OsProxy_Readlink_Call) RunAndReturn(run func(name string) (string, error)) *OsProxy_Readlink_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type OsProxy
func (_mock *OsProxy) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type OsProxy_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *OsProxy_Expecter) Remove(name interface{}) *OsProxy_Remove_Call {
	return &OsProxy_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *OsProxy_Remove_Call) Run(run func(name string)) *OsProxy_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Remove_Call) Return(err error) *OsProxy_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Remove_Call) RunAndReturn(run func(name string) error) *OsProxy_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type OsProxy
func (_mock *OsProxy) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type OsProxy_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *OsProxy_Expecter) RemoveAll(path interface{}) *OsProxy_RemoveAll_Call {
	return &OsProxy_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *OsProxy_RemoveAll_Call) Run(run func(path string)) *OsProxy_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_RemoveAll_Call) Return(err error) *OsProxy_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_RemoveAll_Call) RunAndReturn(run func(path string) error) *OsProxy_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type OsProxy
func (_mock *OsProxy) Rename(oldpath string, newpath string) error {
	ret := _mock.Called(oldpath, newpath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldpath, newpath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type OsProxy_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldpath string
//   - newpath string
func (_e *OsProxy_Expecter) Rename(oldpath interface{}, newpath interface{}) *OsProxy_Rename_Call {
	return &OsProxy_Rename_Call{Call: _e.mock.On("Rename", oldpath, newpath)}
}

func (_c *OsProxy_Rename_Call) Run(run func(oldpath string, newpath string)) *OsProxy_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OsProxy_Rename_Call) Return(err error) *OsProxy_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Rename_Call) RunAndReturn(run func(oldpath string, newpath string) error) *OsProxy_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type OsProxy
func (_mock *OsProxy) Stat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OsProxy_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type OsProxy_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *OsProxy_Expecter) Stat(name interface{}) *OsProxy_Stat_Call {
	return &OsProxy_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *OsProxy_Stat_Call) Run(run func(name string)) *OsProxy_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OsProxy_Stat_Call) Return(v os.FileInfo, err error) *OsProxy_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *OsProxy_Stat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *OsProxy_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Symlink provides a mock function for the type OsProxy
func (_mock *OsProxy) Symlink(oldname string, newname string) error {
	ret := _mock.Called(oldname, newname)

	if len(ret) == 0 {
		panic("no return value specified for Symlink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldname, newname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OsProxy_Symlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Symlink'
type OsProxy_Symlink_Call struct {
	*mock.Call
}

// Symlink is a helper method to define mock.On call
//   - oldname string
//   - newname string
func (_e *OsProxy_Expecter) Symlink(oldname interface{}, newname interface{}) *OsProxy_Symlink_Call {
	return &OsProxy_Symlink_Call{Call: _e.mock.On("Symlink", oldname, newname)}
}

func (_c *OsProxy_Symlink_Call) Run(run func(oldname string, newname string)) *OsProxy_Symlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OsProxy_Symlink_Call) Return(err error) *OsProxy_Symlink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OsProxy_Symlink_Call) RunAndReturn(run func(oldname string, newname string) error) *OsProxy_Symlink_Call {
	_c.Call.Return(run)
	return _c
}
