// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCommand creates a new instance of Command. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *Command {
	mock := &Command{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

type Command_Expecter struct {
	mock *mock.Mock
}

func (_m *Command) EXPECT() *Command_Expecter {
	return &Command_Expecter{mock: &_m.Mock}
}

// PrintableCommandArgs provides a mock function for the type Command
func (_mock *Command) PrintableCommandArgs() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrintableCommandArgs")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Command_PrintableCommandArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintableCommandArgs'
type Command_PrintableCommandArgs_Call struct {
	*mock.Call
}

// PrintableCommandArgs is a helper method to define mock.On call
func (_e *Command_Expecter) PrintableCommandArgs() *Command_PrintableCommandArgs_Call {
	return &Command_PrintableCommandArgs_Call{Call: _e.mock.On("PrintableCommandArgs")}
}

func (_c *Command_PrintableCommandArgs_Call) Run(run func()) *Command_PrintableCommandArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_PrintableCommandArgs_Call) Return(s string) *Command_PrintableCommandArgs_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Command_PrintableCommandArgs_Call) RunAndReturn(run func() string) *Command_PrintableCommandArgs_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type Command
func (_mock *Command) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Command_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Command_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Command_Expecter) Run() *Command_Run_Call {
	return &Command_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Command_Run_Call) Run(run func()) *Command_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_Run_Call) Return(err error) *Command_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Command_Run_Call) RunAndReturn(run func() error) *Command_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunAndReturnExitCode provides a mock function for the type Command
func (_mock *Command) RunAndReturnExitCode() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunAndReturnExitCode")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Command_RunAndReturnExitCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAndReturnExitCode'
type Command_RunAndReturnExitCode_Call struct {
	*mock.Call
}

// RunAndReturnExitCode is a helper method to define mock.On call
func (_e *Command_Expecter) RunAndReturnExitCode() *Command_RunAndReturnExitCode_Call {
	return &Command_RunAndReturnExitCode_Call{Call: _e.mock.On("RunAndReturnExitCode")}
}

func (_c *Command_RunAndReturnExitCode_Call) Run(run func()) *Command_RunAndReturnExitCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_RunAndReturnExitCode_Call) Return(n int, err error) *Command_RunAndReturnExitCode_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Command_RunAndReturnExitCode_Call) RunAndReturn(run func() (int, error)) *Command_RunAndReturnExitCode_Call {
	_c.Call.Return(run)
	return _c
}

// RunAndReturnTrimmedCombinedOutput provides a mock function for the type Command
func (_mock *Command) RunAndReturnTrimmedCombinedOutput() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunAndReturnTrimmedCombinedOutput")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Command_RunAndReturnTrimmedCombinedOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAndReturnTrimmedCombinedOutput'
type Command_RunAndReturnTrimmedCombinedOutput_Call struct {
	*mock.Call
}

// RunAndReturnTrimmedCombinedOutput is a helper method to define mock.On call
func (_e *Command_Expecter) RunAndReturnTrimmedCombinedOutput() *Command_RunAndReturnTrimmedCombinedOutput_Call {
	return &Command_RunAndReturnTrimmedCombinedOutput_Call{Call: _e.mock.On("RunAndReturnTrimmedCombinedOutput")}
}

func (_c *Command_RunAndReturnTrimmedCombinedOutput_Call) Run(run func()) *Command_RunAndReturnTrimmedCombinedOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_RunAndReturnTrimmedCombinedOutput_Call) Return(s string, err error) *Command_RunAndReturnTrimmedCombinedOutput_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Command_RunAndReturnTrimmedCombinedOutput_Call) RunAndReturn(run func() (string, error)) *Command_RunAndReturnTrimmedCombinedOutput_Call {
	_c.Call.Return(run)
	return _c
}

// RunAndReturnTrimmedOutput provides a mock function for the type Command
func (_mock *Command) RunAndReturnTrimmedOutput() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunAndReturnTrimmedOutput")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Command_RunAndReturnTrimmedOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAndReturnTrimmedOutput'
type Command_RunAndReturnTrimmedOutput_Call struct {
	*mock.Call
}

// RunAndReturnTrimmedOutput is a helper method to define mock.On call
func (_e *Command_Expecter) RunAndReturnTrimmedOutput() *Command_RunAndReturnTrimmedOutput_Call {
	return &Command_RunAndReturnTrimmedOutput_Call{Call: _e.mock.On("RunAndReturnTrimmedOutput")}
}

func (_c *Command_RunAndReturnTrimmedOutput_Call) Run(run func()) *Command_RunAndReturnTrimmedOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_RunAndReturnTrimmedOutput_Call) Return(s string, err error) *Command_RunAndReturnTrimmedOutput_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Command_RunAndReturnTrimmedOutput_Call) RunAndReturn(run func() (string, error)) *Command_RunAndReturnTrimmedOutput_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Command
func (_mock *Command) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Command_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Command_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Command_Expecter) Start() *Command_Start_Call {
	return &Command_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Command_Start_Call) Run(run func()) *Command_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_Start_Call) Return(err error) *Command_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Command_Start_Call) RunAndReturn(run func() error) *Command_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type Command
func (_mock *Command) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Command_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type Command_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *Command_Expecter) Wait() *Command_Wait_Call {
	return &Command_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *Command_Wait_Call) Run(run func()) *Command_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_Wait_Call) Return(err error) *Command_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Command_Wait_Call) RunAndReturn(run func() error) *Command_Wait_Call {
	_c.Call.Return(run)
	return _c
}
