// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCommandLocator creates a new instance of CommandLocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandLocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandLocator {
	mock := &CommandLocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommandLocator is an autogenerated mock type for the CommandLocator type
type CommandLocator struct {
	mock.Mock
}

type CommandLocator_Expecter struct {
	mock *mock.Mock
}

func (_m *CommandLocator) EXPECT() *CommandLocator_Expecter {
	return &CommandLocator_Expecter{mock: &_m.Mock}
}

// LookPath provides a mock function for the type CommandLocator
func (_mock *CommandLocator) LookPath(file string) (string, error) {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for LookPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(file)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(file)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommandLocator_LookPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookPath'
type CommandLocator_LookPath_Call struct {
	*mock.Call
}

// LookPath is a helper method to define mock.On call
//   - file string
func (_e *CommandLocator_Expecter) LookPath(file interface{}) *CommandLocator_LookPath_Call {
	return &CommandLocator_LookPath_Call{Call: _e.mock.On("LookPath", file)}
}

func (_c *CommandLocator_LookPath_Call) Run(run func(file string)) *CommandLocator_LookPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CommandLocator_LookPath_Call) Return(s string, err error) *CommandLocator_LookPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CommandLocator_LookPath_Call) RunAndReturn(run func(file string) (string, error)) *CommandLocator_LookPath_Call {
	_c.Call.Return(run)
	return _c
}
