// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	bytes "bytes"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Send provides a mock function with given fields: buffer
func (_m *Client) Send(buffer *bytes.Buffer) {
	_m.Called(buffer)
}
