// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bytes"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type Client
func (_mock *Client) Send(buffer *bytes.Buffer) {
	_mock.Called(buffer)
	return
}

// Client_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Client_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - buffer *bytes.Buffer
func (_e *Client_Expecter) Send(buffer interface{}) *Client_Send_Call {
	return &Client_Send_Call{Call: _e.mock.On("Send", buffer)}
}

func (_c *Client_Send_Call) Run(run func(buffer *bytes.Buffer)) *Client_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bytes.Buffer
		if args[0] != nil {
			arg0 = args[0].(*bytes.Buffer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_Send_Call) Return() *Client_Send_Call {
	_c.Call.Return()
	return _c
}

func (_c *Client_Send_Call) RunAndReturn(run func(buffer *bytes.Buffer)) *Client_Send_Call {
	_c.Run(run)
	return _c
}
